# Form implementation generated from reading ui file './hackathon.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1069, 520)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: rgb(131, 131, 131);\n"
"    font-family: \"Segoe UI\";\n"
"}")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 371, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(198, 131, 36);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(410, 30, 631, 471))
        self.stackedWidget.setStyleSheet("QStackedWidget{\n"
"    background-color: rgb(48, 48, 48);\n"
"    border-radius: 30px;\n"
"    border: 1px solid #4a4a4a;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_2 = QtWidgets.QLabel(parent=self.page_3)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"color: rgb(195, 195, 195);\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(180, 170, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(198, 131, 36);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #D99532; \n"
"    padding: 8px 18px;         \n"
"    border: 2px solid #FFD194; \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #A66B1B; \n"
"    padding: 12px 22px;        \n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.page_3)
        self.pushButton_5.setGeometry(QtCore.QRect(180, 280, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: rgb(198, 131, 36);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #D99532; \n"
"    padding: 8px 18px;         \n"
"    border: 2px solid #FFD194; \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #A66B1B; \n"
"    padding: 12px 22px;        \n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_3)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 170, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"background-color: rgb(203, 0, 3);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(224, 0, 4); \n"
"    padding: 8px 18px;         \n"
"    border: 2px solid rgb(255, 70, 70); \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(176, 0, 3); \n"
"    padding: 12px 22px;        \n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_4.setGeometry(QtCore.QRect(330, 170, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 185, 31);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(29, 219, 36); \n"
"    padding: 8px 18px;         \n"
"    border: 2px solid rgb(32, 255, 77); \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(36, 193, 25); \n"
"    padding: 12px 22px;        \n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 300, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: rgb(203, 203, 2);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(229, 229, 4); \n"
"    padding: 8px 18px;         \n"
"    border: 2px solid rgb(231, 255, 10); \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(174, 174, 3); \n"
"    padding: 12px 22px;        \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 40, 511, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: rgb(198, 131, 36);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_7.setGeometry(QtCore.QRect(20, 400, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"background: transparent;\n"
"border: 0.5px solid rgb(102, 102, 102);\n"
"}\n"
"QPushButton:hover{\n"
"color: rgb(131, 131, 131);\n"
"border: 1px solid rgb(99, 99, 99);\n"
"}\n"
"QPushButton:pressed{\n"
"color: rgb(71, 71, 71);\n"
"border: 1px solid rgb(87, 87, 87);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.page)
        self.pushButton_12.setGeometry(QtCore.QRect(330, 300, 281, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color: rgb(102, 102, 102);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(116, 116, 116); \n"
"    padding: 8px 18px;         \n"
"    border: 2px solid rgb(151, 155, 160); \n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgb(74, 74, 74); \n"
"    padding: 12px 22px;        \n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_8.setGeometry(QtCore.QRect(490, 210, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(23)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("/* 1. Default \'OFF\' State */\n"
"QPushButton {\n"
"    background-color: #e74c3c; /* Red */\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    padding: 5px;\n"
"    border: 3px solid black;\n"
"}\n"
"\n"
"/* 2. \'OFF\' State while Hovering */\n"
"QPushButton:hover {\n"
"    background-color: #ff5e4d; /* Lighter Red */\n"
"}\n"
"\n"
"/* 3. \'ON\' State (The Fix) */\n"
"/* This covers both normal \'ON\' and \'ON\' while hovering */\n"
"QPushButton:checked, \n"
"QPushButton:checked:hover {\n"
"    background-color: #2ecc71; /* Solid Green */\n"
"    color: white;\n"
"}\n"
"\n"
"/* 4. Optional: A slightly darker green when clicking to turn OFF */\n"
"QPushButton:checked:pressed {\n"
"    background-color: #27ae60;\n"
"}")
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_3 = QtWidgets.QLabel(parent=self.page_2)
        self.label_3.setGeometry(QtCore.QRect(170, 30, 291, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"background-color: rgb(198, 131, 36);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.page_2)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 411, 71))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"background-color: rgb(198, 131, 36);\n"
"border: 3px solid;\n"
"border-radius: 20px;\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.stackedWidget.addWidget(self.page_2)
        self.textEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 130, 351, 371))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("QTextEdit{\n"
"background: transparent;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.label.raise_()
        self.textEdit.raise_()
        self.stackedWidget.raise_()

        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Data Dashboard Box"))
        self.label_2.setText(_translate("Dialog", "Customization"))
        self.pushButton.setText(_translate("Dialog", "Colors"))
        self.pushButton_5.setText(_translate("Dialog", "Music"))
        self.pushButton_3.setText(_translate("Dialog", "Red"))
        self.pushButton_4.setText(_translate("Dialog", "Green"))
        self.pushButton_6.setText(_translate("Dialog", "Yellow"))
        self.pushButton_2.setText(_translate("Dialog", "Choose your color:"))
        self.pushButton_7.setText(_translate("Dialog", "Back"))
        self.pushButton_12.setText(_translate("Dialog", "None"))
        self.pushButton_8.setText(_translate("Dialog", "OFF"))
        self.label_3.setText(_translate("Dialog", "Music"))
        self.label_4.setText(_translate("Dialog", "Turn on/off music"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Welcome to Data Bashboard Box, where you can customize your data dashboard, and to see all of the newest and trending items on Amazon. The Data Dashboard shows the selling rates and the reviews of the items you want to see.</span></p></body></html>"))
